name: Build SimKick

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
    
    - name: Show Xcode version
      run: xcodebuild -version
    
    - name: Build for Debug
      run: xcodebuild -scheme simkick -configuration Debug -destination "platform=macOS,arch=arm64" build
    
    - name: Build for Release
      run: xcodebuild -scheme simkick -configuration Release -destination "platform=macOS,arch=arm64" build
    
    - name: Archive Release build
      run: |
        mkdir -p build
        xcodebuild -scheme simkick -configuration Release -destination "platform=macOS,arch=arm64" -archivePath ./build/SimKick.xcarchive archive
    
    - name: Export app
      run: xcodebuild -exportArchive -archivePath ./build/SimKick.xcarchive -exportPath ./build/export -exportOptionsPlist ./export-options.plist
      continue-on-error: true
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: simkick-builds
        path: |
          build/
        retention-days: 30